name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código do repositório
      - uses: actions/checkout@v4

      # 2. Constrói o site usando o contêiner do Jekyll
      - name: Build the site in the Jekyll container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # 3. Fazer upload do build (_site) como artefato
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1
        with:
          name: site-build
          path: _site
