name: Deploy HTML site to GitHub Pages

on:
  push:
    branches:
      - main  # O pipeline será acionado quando houver um push na branch main
  pull_request:
    branches:
      - main  # Ou quando um pull request for criado/atualizado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Diretório onde estão seus arquivos HTML, geralmente a raiz
