stages:
  - build
  - test
  - analyze

build:
  stage: build
  script:
    - echo "Compilando o código..."
    - make build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Executando testes..."
    - make test

analyze:
  stage: analyze
  script:
    - echo "Analisando a qualidade do código..."
    - pylint src/
